apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Cesar
  annotations:
    github.com/project-slug: Cesar-Villegas/Cesar
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: guests
